#!/bin/sh

# This script does personal backups to a rsync backup server. You will end up
# with a 7 day rotating incremental backup. The incrementals will go
# into subdirectories named after the day of the week, and the current
# full backup goes into a directory called "current"
# tridge@linuxcare.com

# directory to backup
BDIR="/c"

# excludes file - this contains a wildcard pattern per line of files to exclude
EXCLUDE=/home/$USER/backup/excludes

# the name of the backup machine
BSERVER=192.168.2.5

# your password on the backup server
#export RSYNC_PASSWORD=

########################################################################

BACKUPDIR=`date +%A`
OPTS="-vv --force --ignore-errors --delete-excluded --exclude-from=$EXCLUDE
      --delete --backup --backup-dir=/$BACKUPDIR -a"

# uncomment for debugging
#OPTS="-n "$OPTS

export PATH=$PATH:/bin:/usr/bin:/usr/local/bin

# the following line clears the last weeks incremental directory
[ -d $HOME/emptydir ] || mkdir $HOME/emptydir
rsync --delete -a $HOME/emptydir/ $BSERVER::$HOSTNAME/$BACKUPDIR/
rmdir $HOME/emptydir

# now the actual transfer
rsync $OPTS "$BDIR" $BSERVER::$HOSTNAME/current
