#!/bin/bash

DEST=$HOME/src/github/music/ncspot

if [[ -d "${DEST}.old" ]]; then
rm -rf "${DEST}.old"
fi

if [[ -d "${DEST}" ]]; then
mv "$DEST" "${DEST}.old"
fi

sudo apt install -y libdbus-1-dev libncursesw5-dev libpulse-dev libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

git clone https://github.com/hrkfdn/ncspot.git "$DEST"
cd "$DEST"

rustup update stable

cat >> Cargo.toml << 'EOF'
[patch.crates-io]
librespot = { git = "https://github.com/librespot-org/librespot" }
librespot-core = { git = "https://github.com/librespot-org/librespot" }
librespot-playback = { git = "https://github.com/librespot-org/librespot" }
librespot-metadata = { git = "https://github.com/librespot-org/librespot" }
librespot-protocol = { git = "https://github.com/librespot-org/librespot" }
librespot-audio = { git = "https://github.com/librespot-org/librespot" }
EOF

rm -f Cargo.lock
cargo update
cargo build --release

mkdir -p ~/.cargo/bin
cp target/release/ncspot ~/.cargo/bin/ncspot
