#!/usr/local/bin/bash

if [ "$OSTYPE" == "cygwin" ]; then
    XBOXPATH="/c/xbox/apps/ccxstream-1.0.15-win"
fi

if [ "$OSTYPE" == "linux-gnu" ]; then
    XBOXPATH="/usr/local/bin"
fi
HOST="127.0.0.1"

function ccxStart()
{
    if [ "$OSTYPE" == "cygwin" ]; then
        ccxStartWindows
    fi

    if [ "$OSTYPE" == "linux-gnu" ]; then
        ccxStartLinux
    fi
}


function ccxStartWindows()
{
    if [ ! -f "$XBOXPATH/ccxstream.exe" ]; then
    echo "ccxstream not found in $XBOXPATH"
    exit 1;
    fi

   SHARES="-S Pictures=c:\\Docume~1\\Alluse~1\Documents\\MyPict~1"

   if [ -d "/cygdrive/d" ]; then
       SHARES=$SHARES" -S cdrom=d:\\"
   fi
   if [ -d "/cygdrive/z" ]; then
       SHARES=$SHARES" -S Z=z:\\"
   fi

   if [ -d "/cygdrive/m" ]; then
       SHARES=$SHARES" -S M=m:\\"
   fi
   SHARES=$SHARES" -S torrents=c:\\torrents"

   echo "$SHARES"

   $XBOXPATH/ccxstream.exe -L -l $HOST -f -r c:\\xbox $SHARES
}

function ccxStartLinux()
{
    if [ ! -f "$XBOXPATH/ccxstream" ]; then
        echo "ccxstream not found in $XBOXPATH"
        exit 1;
    fi

   $XBOXPATH/ccxstream -L -l 192.168.2.3 -f -r /space/nelson/torrents -S games=/home/nelson/games
}

function ccxStop()
{
   echo `psk ccxstream`
}

function usage()
{
   echo "Usage: $0 { START | STOP | RESETART } [HOSTIP] "
   exit 1;
}


if [ "$1" == "" ]; then
    usage
fi

if [ -n "$2" ]; then
    HOST=$2
fi

if [ "$1" == "start" ]; then
    ccxStart
   exit 0;
fi

if [ "$1" == "stop" ]; then
    ccxStop
   exit 0;
fi

if [ "$1" == "restart" ]; then
    ccxStop
    ccxStart
   exit 0;
fi

#usage


