#!/usr/bin/bash

XBOXPATH="/c/xbox"
HOST="127.0.0.1"


function ccxStart()
{
   $XBOXPATH/ccxstream.exe -L -l $HOST -f -r c:\\xbox\\media \
       -S "Pictures2"="c:\Documents and Settings\Pabz\My Documents\My Pictures" \
       -S "mp3_2"="c:\mp3"
}

function ccxStop()
{
   echo `psk ccxstream`
}


if [ ! -f "$XBOXPATH/ccxstream.exe" ]; then
   echo "ccxstream not found in $XBOXPATH"
   exit 1;
fi

if [ -z "$1" ]; then
   echo "Usage: $0 { START | STOP | RESETART } [HOSTIP] "
   exit 1;
fi

if [ -n "$2" ]; then
    HOST=$2
fi

if [ "$1" == "start" ]; then
    ccxStart
fi

if [ "$1" == "stop" ]; then
    ccxStop
fi

if [ "$1" == "restart" ]; then
    ccxStop
    ccxStart
fi
