#!/bin/bash

CONKY='/usr/bin/conky'
CONKY_OPTS='-q'
COMMAND_RE="$CONKY $CONKY_OPTS"

start () {
    #$CONKY $CONKY_OPTS 2> /dev/null
    $CONKY $CONKY_OPTS 
    echo "conky started"
}

stop () {
    OUT=`ps -eaf | grep "$COMMAND_RE"`
    if [ -n "$OUT" ]; then
        echo "$OUT"
        pkill conky
    fi
}

status() {
    OUT=`ps -eaf | grep "$COMMAND_RE"`
    if [ -n "$OUT" ]; then
        echo "conky is running"
    else
        echo "conky is stopped"
    fi
}

case $1 in
        start)
          start
        ;;
        stop|kill)
          stop
        ;;
        restart|reload)
          stop
          sleep 3
          start
        ;;
        status)
          status
        ;;
        *)
          echo $"Invalid option. Usage: $0 [start|stop|kill|restart|reload]."
        ;;
esac

