#!/bin/bash

# Taken from https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/sb-volume

# Prints the current volume or  if muted.

case $BUTTON in
	1) setsid -f "alacritty" -e pulsemixer ;;
	2) playerctl play-pause;;
	4) playerctl volume 0.02+ ;;
	5) playerctl volume 0.02- ;;
	3) notify-send " Volume module" "\- Shows volume ,   if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# vol will be a number between 0 and 1
vol="$(pulsemixer --get-volume | cut -d ' ' -f1)"

# convert volume to percent
#
if [[ "$vol" -gt "70" ]]; then
	icon=""
elif [[ "$vol" -lt "30" ]]; then
	icon=""
else
	icon=""
fi

echo "$icon $vol%"
