#!/bin/bash

# from https://github.com/linuxdabbler/personal-dot-files/blob/master/scripts/cpu.sh

# icons depend on nerdfonts being installed
cpu() {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    echo -e "  $cpu%"
}
echo " $(cpu)"

case $BUTTON in
	1) notify-send "CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | sed 11q)" ;;
	2) setsid "alacritty" -e htop ;;
	3) notify-send "/usr/local/bin/cpu.sh" ;;
esac
