#!/bin/bash

# from https://github.com/linuxdabbler/personal-dot-files/blob/master/scripts/cpu.sh

# icons depend on nerdfonts being installed
echo " $(mpstat 1 1 | grep Average | sed 's/  */ /g' | cut -d' ' -f3)"

case $BUTTON in
	1) notify-send "CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | sed 11q)" ;;
	2) setsid "alacritty" -e gotop ;;
esac
