#!/bin/sh

# Taken from https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/sb-volume

# Prints the current volume or  if muted.

case $BUTTON in
	1) setsid -f "alacritty" -e pulsemixer ;;
	2) playerctl play-pause;;
	4) playerctl volume 0.02+ ;;
	5) playerctl volume 0.02- ;;
	3) notify-send " Volume module" "\- Shows volume ,   if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(playerctl status) = "Paused" ] && echo  && exit

# vol will be a number between 0 and 1
vol="$(playerctl volume)"

# convert volume to percent
#
# divide by 1 to convert to integer
vol=`echo "scale=0; 100 * $vol / 1" | bc -l`

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

echo "$icon $vol%"
