#!/bin/sh

# originally from here: https://github.com/joestandring/dwm-bar#dwm_weather

# A dwm_bar function to print the weather from wttr.in
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: curl

LOCATION=Tollarp

case $BUTTON in
    2) setsid "alacritty" -t "scratchpad"  -o window.dimensions.columns=130 -o window.dimensions.lines=46 -e zsh -c "curl -s wttr.in/$LOCATION; zsh" ;;
esac


DATA=$(curl -s wttr.in/$LOCATION?format=1)
echo "${SEP1} ${DATA} ${SEP2}"
