#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 list_of_flv_files"
    exit 1
fi

# video encoding bit rate
V_BITRATE=800

MENC_OPTS="-ovc xvid -xvidencopts bitrate=$V_BITRATE:autoaspect"

# audio to mp3
AUDIO="-oac mp3lame -lameopts fast:preset=standard"

while [ "$1" ]; do
    if file "$1" | grep -q "Macromedia Flash Video"; then
        mencoder "$1" $MENC_OPTS -vf pp=lb  $AUDIO -o "`basename $1 .flv`.avi"
    else
        echo "$1 is not Flash Video. Skipping"
    fi
    shift
done
