#!/usr/local/bin/perl -w

package main;

use strict;
use File::Basename;
use Getopt::Long;

my $VERSION = '$Revision: 1.3 $';

my $SCRIPTNAME = basename ($0);

my $USAGE = <<USAGE_END;
Usage: $SCRIPTNAME [options]

  Version: $VERSION

  Displays current load for all Blade 1000 machines on network.

  OPTIONS
    --debug    Outputs information to aid in debugging.
    --users    Displays the primary user of the machine.
USAGE_END

my %machine;
my %machineByLoad;
my $assignDHosts =  0;
my $distcc =  0;
my $helpShow;
my $showUser;

main ();

#------------------------------------------------------------------------------
#
#
#------------------------------------------------------------------------------
sub trim
{
    my @strings = @_;
    for (@strings)
    {
        s/^\s+//;
        s/\s+$//;
    }
    return wantarray ? @strings : $strings[0];
}


#------------------------------------------------------------------------------
#
#
#------------------------------------------------------------------------------
sub main
{
    if (!GetOptions ('assign' => \$assignDHosts,
                     'distcc' => \$distcc,
                     'help'   => \$helpShow,
                     'users'  => \$showUser))
    {
        die "ERROR: bad options in command line\n";
    }

    if ($helpShow)
    {
        print $USAGE;
        exit 0;
    }

    open (YP, "ypcat hosts.byaddr |")
        || die "ypcat failed!";

    while (<YP>)
    {
        my $line = $_;
        chomp ($line);

        # look only for Blade 1000 machines
        if ($line !~ /B1000/) { next; }

        #print $line, "\n";

        # ypcat output uses tabs, so substr wont work
        if ($line =~ /^([\d\.]+)\s+(\w+)\s+#\s+(\S+)\s+(\S+)\s+(.+)/)
        {
            if (defined ($1) && defined ($2) && defined ($3)
                && defined ($4) && defined ($5))
            {
                $machine {$2} {'ip'}    = $1;
                $machine {$2} {'descr'} = $3;
                $machine {$2} {'type'}  = $4;
                $machine {$2} {'user'}  = $5;
            }
        }
    }
    close (YP);

    # get load values
    foreach my $host (sort keys %machine)
    {
        my $op = `rup $host`;

        if ($op =~ /load average: ([\d\.]+)/)
        {
            $machine {$host} {'load'} = $1;
        }
        else
        {
            $machine {$host} {'load'} = 'unknown';
        }
        $machineByLoad {$1 . $host} = $host;
    }

    # output information sorted by load
    my @distcchosts = ();
    my $count = 0;
    foreach my $load (sort keys %machineByLoad)
    {
        my $host = $machineByLoad {$load};
        if ($count < 4)
        {
            push (@distcchosts, $host);
        }

        if ($distcc)
        {
            my $op = `rsh $host /home/sw/bin/psgrep /distcc/`;
            my @op = split (/\n/, $op);
            @op = grep (/\/home\/sw\/bin\/distcc/, @op);

            if ($#op + 1> 0)
            {
                $machine {$host} {'distcc'} = "distcc";
            }
        }

        printf "%-10s %-6s %-18s %-7s",
               $host, $machine {$host} {'load'}, $machine {$host} {'type'};

        if ($showUser)
        {
            print $machine {$host} {'user'};
        }

        if ($distcc)
        {
            printf " %-7s", $machine {$host}{'distcc'};
        }

        $count++;
        print "\n";
    }

    my $ip = join (" ", @distcchosts);

    if ($assignDHosts)
    {
        system ("echo \"$ip\" > $ENV{'HOME'}/.distcc/hosts");
    }

    print "\ndistcc hosts: ", $ip, "\n";

}
