#!/usr/local/bin/perl -w

use strict;
use MIME::QuotedPrint;
use MIME::Base64;
use Mail::Sendmail 0.75; # doesn't work with v. 0.74!
use Time::localtime;
use File::stat;
use File::Basename;

my $usage = <<USAGE_END;
usage: $0 TO SUBJECT FILENAME

  Emails a file.

USAGE_END

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------
sub timestampGet
{
    my $file = shift;
    my $timestamp = ctime (stat ($file)->mtime);
    return $timestamp;
}

if ((!defined $ARGV [0]) || (!defined $ARGV [1]) || (!defined $ARGV [2]))
{
    die $usage;
}

print "  sending to: ", $ARGV [0], "\n";
print "  subject:    ", $ARGV [1], "\n";
print "  file:       ", $ARGV [2], "\n";

my %mail = (To      => $ARGV[0],
            From    => 'nelson.loyola@galazar.com',
            Subject => $ARGV[1]);

my $boundary = "====" . time() . "====";

$mail{'content-type'} = "multipart/mixed; boundary=\"$boundary\"";

my $file = $ARGV [2];
my $prefix;
my $basename;
my $suffix;

($basename, $prefix) = fileparse ($file);

my $message = encode_qp( "here is the file: " . timestampGet ($file) );


open (F, $file) or die "Cannot read $file: $!";
binmode F; undef $/;
$mail{body} = encode_base64(<F>);
close F;

$boundary = '--'.$boundary;
$mail{body} = <<END_OF_BODY;
$boundary
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

$message
$boundary
Content-Type: application/octet-stream; name="$basename"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="$basename"

$mail{body}
$boundary--
END_OF_BODY

sendmail (%mail) || print "Error: $Mail::Sendmail::error\n";
