#!/bin/bash

#set -o verbose

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT [OPTIONS] QRY

OPTIONS
  -d DBNAME   The name of the database.
  -H DBHOST   The hostname of the machine running the MySQL server. Defaults to
              localhost if not specified.
  -u DBUSER   The user to use on the MySQL server.
  -o FNAME    File name to save output to.
  -p PWD      The password to use on the MySQL server.
  -h          Help text.
"

MYSQL=/usr/bin/mysql
SED=/bin/sed
DBHOST="localhost"

while getopts "d:H:u:p:o:h" OPTION; do
    case $OPTION in
        d)
            DBNAME="$OPTARG"
            shift $((OPTIND-1)); OPTIND=1
            ;;
        H)
            DBHOST="$OPTARG"
            shift $((OPTIND-1)); OPTIND=1
            ;;
        u)
            DBUSER="$OPTARG"
            shift $((OPTIND-1)); OPTIND=1
            ;;
        o)
            OUTPUT="$OPTARG"
            shift $((OPTIND-1)); OPTIND=1
            ;;
        p)
            DBPWD="$OPTARG"
            shift $((OPTIND-1)); OPTIND=1
            ;;
        h)
            echo "$USAGE"
            exit 1
            ;;
        ?)
            echo "$USAGE"
            exit 1
            ;;
    esac
done

QUERY=$1

if [ -z "$DBUSER" ]; then
    echo "ERROR: user not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBPWD" ]; then
    echo "ERROR: password not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$DBNAME" ]; then
    echo "ERROR: database name not specified"
    echo "$USAGE"
    exit
fi

if [ -z "$QUERY" ]; then
    echo "ERROR: query not specified"
    echo "$USAGE"
    exit
fi

if [ ! -z "$OUTPUT" ]
then
   $MYSQL -h$DBHOST -u$DBUSER -p$DBPWD -D$DBNAME -B -e "$QUERY" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g' > $OUTPUT
else
   $MYSQL -h$DBHOST -u$DBUSER -p$DBPWD -D$DBNAME -B -e "$QUERY" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g'
fi

exit 0
