#!/bin/bash

#set -o verbose

ARGS=5
E_BADARGS=85

if [ $# -lt $ARGS ]  # Correct number of arguments passed to script?
then
  echo "Usage: `basename $0` HOST USER PWD DBNAME QUERY [OUTFILE]"
  exit $E_BADARGS
fi

MYSQL=/usr/bin/mysql
SED=/bin/sed
HOST=$1
USER=$2
PWD=$3
DBNAME=$4
QUERY="$5"
OUTPUT=$6
PIPE=

if [ ! -z "$OUTPUT" ]
then
   $MYSQL -h$HOST -u$USER -p$PWD -D$DBNAME -B -e "$QUERY" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g' > $OUTPUT
else
   $MYSQL -h$HOST -u$USER -p$PWD -D$DBNAME -B -e "$QUERY" | $SED 's/\t/\",\"/g;s/^/\"/;s/$/\"/;s/\n//g'
fi


exit 0
