#!/usr/local/bin/perl -w

#rename - Larry's filename fixer
$op = shift or die "Usage: rename expr [files]\n";
chomp (@ARGV = <STDIN>) unless @ARGV;
for (@ARGV)
{
    $was = $_;
    eval $op;
    die $@ if $@;
    rename ($was,$_) unless $was eq $_;
}

# remove underscores
# rename 's/\_/ /g' *

# capitalize each word's first char, downcase the rest
# rename 's/(\w+)/\u\L$1/g' *

# prompts user, changes foo to bar
# rename 'print "$_: "; s/foo/bar/ if <STDIN> =~ /^y/i' *
