#!/usr/local/bin/perl -w

use strict;
use MIME::QuotedPrint;
use MIME::Base64;
use Mail::Sendmail 0.75; # doesn't work with v. 0.74!
use Time::localtime;
use File::stat;
use File::Basename;

my $usage = <<USAGE_END;
usage: $0 TO_EMAIL

  Emails a file.

USAGE_END

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------
sub timestampGet
{
    my $file = shift;
    my $timestamp = ctime (stat ($file)->mtime);
    return $timestamp;
}

if (!defined $ARGV [0])
{
    die $usage;
}


print "  sending to: ", $ARGV [0], "\n";

my %mail = (To      => $ARGV[0],
            From    => 'nelson.loyola@galazar.com',
            Subject => 'Configuration Update');

my $boundary = "====" . time() . "====";
$mail{'content-type'} = "multipart/mixed; boundary=\"$boundary\"";

system ("/home/nloyola/bin/config_tar");

my $file = "/home/nloyola/config.tar.gz";

my $prefix;
my $basename;
my $suffix;

($basename, $prefix) = fileparse ($file);

my $message = encode_qp( "Configuration snapshot taken: " .
                         timestampGet ($file) );


open (F, $file) or die "Cannot read $file: $!";
binmode F; undef $/;
$mail{body} = encode_base64(<F>);
close F;

$boundary = '--'.$boundary;
$mail{body} = <<END_OF_BODY;
$boundary
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

$message
$boundary
Content-Type: application/octet-stream; name="$basename"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="$basename"

$mail{body}
$boundary--
END_OF_BODY

sendmail(%mail) || print "Error: $Mail::Sendmail::error\n";
