#!/bin/bash

prog=$"VNC Server"
geom="1024x768"

if [ "$USER" == "loyola" ]; then
    #VNCSERVER="$HOME/apps/bin/vncserver"
    VNCSERVER="/usr/bin/vncserver"
else
    VNCSERVER="/usr/bin/vncserver"
fi

if [ ${USER} = "nelson" ]; then
    session=$":1"
    geom="1280x1024"
elif [ ${USER} = "loyola" ]; then
    session=$":1"
    geom=1024x768
elif [ ${USER} = "root" ]; then
    echo "Do not un VNC as root. *smack* bad user..." && exit 0
else
    echo $"${USER} does not have a valid VNC account." && exit
fi

start ()
{
        $VNCSERVER -name ${HOSTNAME} -geometry $geom -depth 24 $session
}

stop () {
        $VNCSERVER -kill $session
}

case $1 in
        start)
          start
        ;;
        stop|kill)
          stop
        ;;
        restart|reload)
          stop
          sleep 3
          start
        ;;
        *)
          echo $"Invalid option. Usage: $0 [start|stop|kill|restart|reload]."
        ;;
esac

