#!/bin/bash

prog=$"VNC Server"
geom="1024x768"

if [ "$HOSTNAME" == "uk0*" ]; then
    VNCSERVER="$HOME/apps/bin/vncserver"
else
    VNCSERVER="/usr/bin/vncserver"
fi

session=$":1"
geom="1280x1024"

#if [ "$HOSTNAME" == "uk0*" -o "$HOSTNAME" == "amber-rv" ]; then
#    geom=1024x768
#fi

if [ ${USER} = "root" ]; then
    echo "Do not un VNC as root. *smack* bad user..." && exit 0
fi

start ()
{
        $VNCSERVER -name ${HOSTNAME} -geometry $geom -depth 24 $session
}

stop () {
        $VNCSERVER -kill $session
}

case $1 in
        start)
          start
        ;;
        stop|kill)
          stop
        ;;
        restart|reload)
          stop
          sleep 3
          start
        ;;
        *)
          echo $"Invalid option. Usage: $0 [start|stop|kill|restart|reload]."
        ;;
esac

