#!/bin/bash

prog=$"VNC Server"
geom="1280x1024"
session=$2

if [ "$USER" == "loyola" ]; then
    #VNCSERVER="$HOME/apps/bin/vncserver"
    VNCSERVER="/usr/bin/vncserver"
else
    VNCSERVER="/usr/bin/vncserver"
fi

if [ ${USER} = "nelson" ]; then
    geom="1280x1024"
elif [ ${USER} = "loyola" ]; then
    geom="1280x1024"
elif [ ${USER} = "root" ]; then
    echo "Do not un VNC as root. *smack* bad user..." && exit 0
fi

start () {
        $VNCSERVER -name ${HOSTNAME} -geometry $geom -depth 24 $session
}

stop () {
        $VNCSERVER -kill $session
}

case $1 in
        start)
          start
        ;;
        stop|kill)
          stop
        ;;
        restart|reload)
          stop
          sleep 3
          start
        ;;
        *)
          echo $"Invalid option. Usage: $0 [start|stop|kill|restart|reload]."
        ;;
esac

