#!/bin/sh

if [ ! -f /usr/bin/playerctl ]; then
    echo "ERROR: playerctl not found!"
    exit 1
fi

case "$1" in
    -i)
        playerctl volume 0.02+;;
    -d)
        playerctl volume 0.02-;;
esac

pkill -RTMIN+2 dwmblocks
