#!/bin/sh

if [ ! -f /home/nelson/bin/pamixer ]; then
    echo "ERROR: pamixer not found!"
    exit 1
fi

case "$1" in
        -i)
            pamixer -i 2;;
        -d)
            pamixer -d 2;;
    esac

pkill -RTMIN+10 dwmblocks
