#!/bin/sh

if [ ! -f /usr/bin/pulsemixer ]; then
    echo "ERROR: pulsemixer not found!"
    exit 1
fi

case "$1" in
    -i)
        pulsemixer --change-volume 2;;
    -d)
        pulsemixer --change-volume -2;;
esac

pkill -RTMIN+2 dwmblocks
