#!/bin/bash --norc

vxsimdir=""
if [ -n "$OSTYPE" ]; then
    if [ "$OSTYPE" == "solaris" ]; then
        vxsimdir = "$P4DIR/proj/swae/vxImage_me_p"
    fi
else
    # assume cygwin
    vxsimdir = "$P4DIR/proj/swae/vxImage_me_pc"
fi

if [ ! -d $vxsimdir ]; then
   echo "cannot find vxsim directory"
   exit 1
fi

cd $vxsimdir
./vxWorks -r 8000000 &
