#!/bin/bash --norc

vxsimdir=""
if [ -z "$OSTYPE" ]; then
   echo "environment variable OSTYPE not defined"
   exit 1
fi

case $OSTYPE in
    solaris*)
        vxsimdir="$P4DIR/proj/swae/vxImage_me_p"
        ;;
    *)
        # assume cygwin
        vxsimdir="$P4DIR/proj/swae/vxImage_me_pc"
        ;;
esac

if [ ! -d $vxsimdir ]; then
   echo "cannot find vxsim directory"
   exit 1
fi

cd $vxsimdir
./vxWorks -r 8000000 &
