#!/usr/bin/bash

if [ -f /usr/local/bin/xemacs ]; then
    XEMACS_PATH=/usr/local/bin
fi

if [ -f $HOME/apps/bin/xemacs ]; then
    XEMACS_PATH=$HOME/apps/bin
fi

result=`($XEMACS_PATH/gnuclient -q $* &) 2>&1 | wc -l | sed 's/ //g'`
if [ "$result" != "0" ]; then
   # need to start XEmacs
   $XEMACS_PATH/xemacs $* &
fi



